services:
  api:
    build: .
    container_name: django_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/api
    command: python manage.py runserver 0.0.0.0:5000
  db:
      image: mongo:latest
      hostname: test_mongodb
      environment:
        - MONGO_INITDB_DATABASE=animal_db
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass
      volumes:
        - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      ports:
        - 27017:27017
