services:
  api:
    build: .
    container_name: django_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=secret-key-para-docker
      - DEBUG=False
      - MONGO_HOST=db
      - MONGO_USER=root
      - MONGO_PASSWORD=senha-forte-docker
      - MONGO_DB=animal_db
    volumes:
      - .:/animals_api
    command: python manage.py runserver 0.0.0.0:5000

  db:
    image: mongo:latest
    container_name: djangoapimongotest-db-1
    ports:
      - "27017:27017"
    hostname: test_mongodb
    environment:
      MONGO_INITDB_DATABASE: animal_db
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      
volumes:
  mongo_data: